# Ensure additional packages are installed

- name: Ensure extra reposistories are present (Ubuntu)
  apt_repository:
    repo="deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} universe multiverse"
    state=present
  when: is_ubuntu

- name: Ensure the APT package cache is updated
  apt:
    update_cache=yes
    cache_valid_time=0
  when: is_debian_or_ubuntu

- name: Ensure additional packages are installed
  apt:
    name={{item}}
    state=present
  with_items:
    - aptitude
    - python-apt
    - sysvinit-utils
    - software-properties-common
    - python-software-properties
    - python-pycurl
  when: is_debian_or_ubuntu
