# slurm-common/defaults/main.yml
---

# Version of SLURM to install; choose among '17.02', '17.11', and '18.08'.
# Only used on RHEL/CentOS 7
slurm_version: '18.08'

SLURM_MASTER_HOST: "{{groups['slurm_master'][0]}}"
SLURM_MASTER_ADDR: "{{hostvars[SLURM_MASTER_HOST].ansible_default_ipv4.address}}"

# XXX: there is really no good default for the accounting host: a host
# name or IP address is needed here, which must be reachable by all
# hosts in the cluster.  Default to `slurmdbd` so if host
# names/aliases are set according to the services that run, everything
# works fine.
SLURM_ACCOUNTING_HOST: "slurmdbd"
SLURM_ACCOUNTING_DB_NAME: "slurm"
SLURM_ACCOUNTING_DB_USER: "slurm"
SLURM_ACCOUNTING_DB_PASS: "ua7diKee"


# defaults used in `slurm.conf`
slurm_fastschedule: 1
slurm_jobacctgatherfrequency: 60
slurm_jobacctgathertype: 'jobacct_gather/linux'
slurm_maxarraysize: 1000
slurm_maxjobcount: 10000
slurm_proctracktype: 'proctrack/linuxproc'
slurm_returntoservice: 2
slurm_selecttype: 'select/cons_res'
slurm_selecttypeparameters: 'CR_Core_Memory'
slurm_taskplugin: 'task/none'
