---

# A list of NFS filesystems to mount.
#
# Each filesystem is defined by a dictionary with the following
# key/value pairs:
#
# - fs: the remote filesystem to mount, in the form server:/path
# - mountpoint: path to the local mountpoint
# - options: mount options, defaults to `rw,async` if not given
# - state: see documentation for Ansible module `mount`; the default value here is `mounted`
#
# For example::
#
#     NFS_MOUNTS:
#       - fs: 'localhost:/export'
#         mountpoint: '/import'
#         options: 'rw,defaults'
#     
# By default, this parameter is the empty list, i.e., no NFS filesystems are mounted.
#
NFS_MOUNTS: []
