---
- name: Common configuration
  hosts: gridengine_master:gridengine_clients
  vars_files:
    - vars/os
  tasks:
    - name: configure /etc/hosts file
      action: template src=gridengine/templates/hosts.j2 dest=/etc/hosts owner=root group=root

    - name: set hostname
      action: command hostname $inventory_hostname

- name: GridEngine masternode Playbook
  hosts: gridengine_master
  vars_files:
    - vars/os
  tasks: 
    - include: slurm/tasks/nfs.yml
    - include: gridengine/tasks/master.yml
  handlers:
    - include: gridengine/handlers/main.yml

- name: GridEngine worker nodes Playbook
  hosts: gridengine_clients
  vars_files:
    - vars/os
  tasks: 
    - include: slurm/tasks/nfs-clients.yml nfsserver=${groups.gridengine_master[0]}
    - include: gridengine/tasks/clients.yml
  handlers:
    - include: gridengine/handlers/main.yml

