---
- name: Jenkins CIS Playbook
  hosts: jenkins
  tasks: 
    - include: common/tasks/ssh_host_based_authentication.yml hosts=${groups.all}
    - include: jenkins/tasks/main.yml
  handlers:
    - include: jenkins/handlers/main.yml