---
- name: Common configuration
  hosts: pbs_master:pbs_clients:maui_master
  vars_files:
    - vars/os
  tasks:
    - include: common/tasks/gc3repo.yml
    - include: common/tasks/hosts.yml hosts=${groups.all}
    - name: set hostname
      action: command hostname $inventory_hostname

- name: PBS masternode Playbook
  hosts: pbs_master
  vars_files:
    - vars/os
  tasks: 
    - include: slurm/tasks/nfs.yml
    - action: nfsexport path=/home dest=/etc/exports clients=${groups.pbs_clients} options=rw,no_root_squash,sync
      notify: reload exports

    - include: pbs+maui/tasks/master.yml
    - include: cluster/tasks/packages.yml
  handlers:
    - include: slurm/handlers/main.yml
    - include: pbs+maui/handlers/main.yml

- name: MAUI masternode Playbook
  hosts: maui_master
  vars_files:
    - vars/os
  tasks: 
    - include: pbs+maui/tasks/maui.yml
  handlers:
    - include: pbs+maui/handlers/main.yml

- name: PBS worker nodes Playbook
  hosts: pbs_clients
  vars_files:
    - vars/os
  tasks: 
    - include: slurm/tasks/nfs-clients.yml nfsserver=${groups.pbs_master[0]} nfspath=/home nfsmount=/home
    - include: pbs+maui/tasks/clients.yml
    - include: cluster/tasks/packages.yml
  handlers:
    - include: pbs+maui/handlers/main.yml

