---
- name: Slurm master Playbook
  hosts: slurm_master
  vars_files:
    - vars/os
  tasks: 
    - include: common/tasks/hosts.yml hosts=${groups.all}
    - include: slurm/tasks/main.yml
    - include: slurm/tasks/nfs.yml
    - include: slurm/tasks/master.yml
    - include: cluster/tasks/packages.yml
  handlers:
    - include: slurm/handlers/main.yml

- name: Slurm worker nodes Playbook
  hosts: slurm_clients
  vars_files:
    - vars/os
  tasks: 
    - include: common/tasks/hosts.yml hosts=${groups.all}
    - include: slurm/tasks/main.yml
    - include: slurm/tasks/nfs-clients.yml nfsserver=${groups.slurm_master[0]}
    - include: cluster/tasks/packages.yml
  handlers:
    - include: slurm/handlers/main.yml

# Get infos with
# ansible -i hostsfile -m setup hostname