# hive/tasks/main.yml
---

- name: Install Hive packages (client)
  tags:
    - hadoop
    - hive
  package:
    name: '{{item}}'
    state: present
  with_items:
    - hive
    # Java JDBC support for PostgreSQL
    - libpostgresql-jdbc-java


- name: Ensure Hive configuration directory exists
  tags:
    - hadoop
    - hive
  file:
    path='{{HIVE_CONF_DIR}}'
    state=directory


- name: Copy Hive/BigTop default configuration files
  tags:
    - hadoop
    - hive
  command:
    'rsync -ax --update --backup /etc/hive/conf.dist/ {{HIVE_CONF_DIR}}/'


- name: Deploy Hive/ElastiCluster configuration files
  tags:
    - hadoop
    - hive
  template:
    src='{{item}}.j2'
    dest='{{HIVE_CONF_DIR}}/{{item}}'
  with_items:
    - hive-env.sh
    - hive-site.xml


- name: Activate Hive/ElastiCluster configuration
  alternatives:
    name='hive-conf'
    link='/etc/hive/conf'
    path='{{HIVE_CONF_DIR}}'


- name: Make Hive settings available to all Hadoop apps
  file:
    path='{{HADOOP_CONF_DIR}}/hive-site.xml'
    src='{{HIVE_CONF_DIR}}/hive-site.xml'
    state=link
