---

# init scripts for `gmetad` and `ganglia-monitor` services do not support the
# `status` action, which makes Ansible's `service:` module fail.
- name: restart gmond
  command: |
    service {{item}} restart
  with_items: '{{ ganglia_gmond_services }}'
  when: '{{is_debian_compatible}} and not {{init_is_systemd}}'


- name: restart gmond
  service:
    name: '{{ item }}'
    state: restarted
  with_items: '{{ ganglia_gmond_services }}'
  when: is_rhel_compatible
