---
- name: Version compatibility check
  fail:
    msg: "Python 2 is only available in Anaconda version 2019.10 or less, but Anaconda {{ anaconda_version }} was requested.  To proceed, please set `anaconda_version` to version 2019.10 or earlier, or set `anaconda_python_version=3` and then retry."
  when: 'anaconda_python_version|int == 2 and anaconda_version.split(".")[0]|int >= 2020'

- name: Download Anaconda installer script
  get_url:
    url: '{{anaconda_installer_url}}'
    dest: '{{anaconda_installer_sh}}'
    owner: root
    group: root
    mode: 0755
    validate_certs: '{{ not insecure_https_downloads|default("no")|bool }}'

- name: Install Anaconda
  command: '{{anaconda_installer_sh}} -b -f -p {{anaconda_home}}'
  args:
    creates: '{{anaconda_home}}/bin/conda'

- name: Delete Anaconda installer script
  file:
    path='{{anaconda_installer_sh}}'
    state=absent
  when: anaconda_cleanup

- name: make Anaconda Python the first match in $PATH
  template:
    src='etc/profile.d/anaconda.sh.j2'
    dest='/etc/profile.d/anaconda{{anaconda_python_version}}.sh'
    mode=0444
    owner=root
    group=root
  when: anaconda_in_path

- name: Make convenience symlink to Anaconda home
  file:
    dest='/opt/anaconda{{anaconda_python_version}}'
    src='{{anaconda_home}}'
    state=link
    owner=root
    group=root
