---

- name: PBS masternode Playbook
  hosts: pbs_master
  roles:
    - role: 'nis'
      NIS_MASTER: '{{groups.pbs_master[0]}}'
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: nfs-server
      NFS_EXPORTS:
      - path: '/home'
        clients: '{{groups.pbs_clients}}'
        options: 'rw,no_root_squash,async'
    - role: hpc-common
  tasks:
    - include: pbs+maui/tasks/master.yml
  handlers:
    - include: common/handlers/main.yml
    - include: pbs+maui/handlers/main.yml

- name: MAUI masternode Playbook
  hosts: maui_master
  tasks:
    - include: pbs+maui/tasks/maui.yml
  handlers:
    - include: pbs+maui/handlers/main.yml

- name: PBS worker nodes Playbook
  hosts: pbs_clients
  roles:
    - role: 'nis'
      NIS_MASTER: '{{groups.pbs_master[0]}}'
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: nfs-client
      NFS_MOUNTS:
      - fs: '{{groups.pbs_master[0]}}:/home'
        mountpoint: '/home'
        options: 'rw,async'
    - role: autofs
    - role: hpc-common
  tasks:
    - include: pbs+maui/tasks/clients.yml
  handlers:
    - include: pbs+maui/handlers/main.yml
