---

- name: Slurm master Playbook
  hosts: slurm_master
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: 'nfs-server'
      NFS_EXPORTS:
        - path: '/home'
          clients: "{{groups.slurm_worker + groups.slurm_submit|default([])}}"
    - slurm-master


- name: Slurm worker nodes Playbook
  hosts: slurm_worker
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'
    - role: autofs
    - slurm-worker


- name: Slurm submit nodes Playbook
  hosts: slurm_submit:slurm_client
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'
    - role: autofs
    - slurm-client


- name: Restart SLURMd after all config is done
  hosts: slurm_worker
  tasks:
    - service:
        name=slurmd
        state=restarted
      when: '{{is_debian_compatible}} and ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}})'
    - service:
        name=slurm-llnl
        state=restarted
      when: '{{is_debian_compatible}} and (not ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}}))'
    - service:
        name=slurmd
        state=restarted
      when: '{{is_rhel7_compatible}}'
    - service:
        name=slurm
        state=restarted
      when: '{{is_rhel6_compatible}}'
