---
- name: SLURM common playbook
  hosts: slurm_master:slurm_submit:slurm_workers
  tasks:
    # RHEL/CentOS 6.x comes with a default "REJECT" last rule which makes NFS
    # servers and SLURM communication fail - disable it altogether until we can
    # configure the entire NFS stack with fixed ports
    - name: Disable firewall (RHEL/CentOS 6.x)
      service:
        name=iptables
        enabled=no
        state=stopped
      when: 'is_rhel6_compatible'


- name: Slurm master Playbook
  hosts: slurm_master
  roles:
    - role: 'nfs-server'
      NFS_EXPORTS:
        - path: '/home'
          clients: "{{groups.slurm_workers + groups.slurm_submit|default([])}}"
    - slurm-master

      
- name: Slurm worker nodes Playbook
  hosts: slurm_workers
  roles:
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'
    - slurm-worker


- name: Slurm submit nodes Playbook
  hosts: slurm_submit:slurm_client
  roles:
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'
    - slurm-client

    
- name: Restart SLURMd after all config is done
  hosts: slurm_workers
  tasks:
    - service:
        name=slurmd
        state=restarted
      when: '{{is_debian_compatible}} and ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}})'
    - service:
        name=slurm-llnl
        state=restarted
      when: '{{is_debian_compatible}} and (not ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}}))'
    - service:
        name=slurmd
        state=restarted
      when: '{{is_rhel7_compatible}}'
    - service:
        name=slurm
        state=restarted
      when: '{{is_rhel6_compatible}}'
