---
- name: Prepare VM for running Ansible
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure Python is installed
      script: |
        install-py2.sh {{ ansible_python_interpreter|default("/usr/bin/python") }}
      args:
        creates: '{{ ansible_python_interpreter|default("/usr/bin/python") }}'
      become: yes

# for local customizations
- import_playbook: before.yml

- name: Common setup for all hosts
  hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Ensure apt-daily is *not* running
      script: |
        no-update-on-reboot.sh
      become: yes
      when: 'is_debian_compatible'
  roles:
    - role: common
    - role: iptables
      # FIXME: should change to 'DROP' when all playbooks register their input ports!
      default_input_policy: 'ACCEPT'
    - role: ntpd
      ntp_server: '{{groups.ntp_master|default([])}}'
    - role: pdsh

# This needs to be run as early as possible as it may need to reboot
# the VM to install driver support
- import_playbook: roles/cuda.yml

# Run all other playbooks one by one, so they get a chance of doing
# their setup depending on configured host groups

# filesystems/storage first so we could in principle use it in compute clusters
- import_playbook: roles/google-local-ssd.yml
- import_playbook: roles/ceph.yml
- import_playbook: roles/glusterfs.yml
- import_playbook: roles/pvfs2.yml
- import_playbook: roles/nfs-server.yml
- import_playbook: roles/azure-files.yml


# now install and set up computing infrastructure
- import_playbook: roles/gridengine.yml
- import_playbook: roles/hadoop.yml
- import_playbook: roles/htcondor.yml
- import_playbook: roles/ipython.yml
- import_playbook: roles/jenkins.yml
- import_playbook: roles/kubernetes.yml
- import_playbook: roles/pbspro.yml
- import_playbook: roles/slurm.yml
- import_playbook: roles/torque.yml

# add-on software
- import_playbook: roles/anaconda.yml
- import_playbook: roles/ansible.yml
- import_playbook: roles/easybuild.yml
- import_playbook: roles/ganglia.yml
- import_playbook: roles/hpc-common.yml
- import_playbook: roles/julia.yml
- import_playbook: roles/r.yml
- import_playbook: roles/rstudio.yml
- import_playbook: roles/samba.yml
- import_playbook: roles/docker.yml

# Jupyter installation comes last, to allow it to pick up any SW that's been
# installed so far (e.g., for kernels, or for ipyparallel)
- import_playbook: roles/jupyterhub.yml

# for local customizations
- import_playbook: after.yml

# if we got to this point, all is well
- name: Report success on cluster creation
  hosts: all
  gather_facts: no
  tasks:
    - name: Mark host as successfully configured
      shell: |
        echo 'done' > '{{ elasticluster.output_dir }}/{{ inventory_hostname }}.log'
      delegate_to: 'localhost'
      # this is necessary as we might not have/want superuser rights
      # where ElastiCluster is running
      become: no
