---

- name: Load distribution-specific parameters
  include: 'init-{{ansible_os_family}}.yml'


# Otherwise `systemctl mask $someservice` fails on RHEL/CentOS7
- name: Temporarily disable SELinux (RHEL-family)
  selinux:
    policy=targeted
    state=permissive
  when: 'is_rhel_compatible'


# need to do this here, as the SLURM packages are not yet installed
- name: Create `slurm` system group
  group:
    name=slurm
    system=yes
  tags: 
    - slurm


- name: Create `slurm` system user 
  user:
    name=slurm
    group=slurm
    system=yes
  tags: 
    - slurm

  
- name: Create work directory {{item}}
  file:
    path='{{item}}'
    state=directory
    owner=slurm
    group=slurm
  with_items:
    - /etc/slurm
    - /var/lib/slurm
    - /var/lib/slurm/checkpoint
    - /var/lib/slurm/slurmctld
    - /var/lib/slurm/slurmd
    - /var/log/slurm
    - /var/run/slurm
    - /var/spool/slurm
  tags: 
    - slurm


# Debian/Ubuntu packages place configuration in `/etc/slurm-llnl` and
# logs in `/var/log/slurm-llnl` -- symlink this to `/etc/slurm` and
# `/var/log/slurm` etc. so we need not worry about varying paths in
# playbooks and config files
- name: Make compatibility symlinks
  file:
    path='{{ item.to }}'
    src='{{ item.from }}'
    state=link
    force=yes
  with_items:
    - { from: '/etc/slurm',     to: '/etc/slurm-llnl' }
    - { from: '/var/lib/slurm', to: '/var/lib/slurm-llnl' }
    - { from: '/var/log/slurm', to: '/var/log/slurm-llnl' }
    - { from: '/var/run/slurm', to: '/var/run/slurm-llnl' }
  when: is_debian_compatible
  tags: 
    - slurm
    - debian


- name: Enable Copr SLURM repo by verdurin
  tags: 
    - slurm
  template:
    src=copr-slurm.repo.j2
    dest='/etc/yum.repos.d/copr-slurm.repo'
    mode=0444
  when: is_rhel_compatible


- include: munge.yml


- name: Deploy SLURM configuration file
  tags: 
    - slurm
  template:
    src=slurm.conf.j2
    dest=/etc/slurm/slurm.conf
    owner=root
    group=root
    mode=0444

- name: Deploy script to suspend cloud instance 
  tags: 
    - slurm
  template:
    src=slurm.suspend.j2
    dest=/etc/slurm/slurm.suspend.sh
    owner=root
    group=root
    mode=0555

- name: Deploy script to resume cloud instance 
  tags: 
    - slurm
  template:
    src=slurm.resume.j2
    dest=/etc/slurm/slurm.resume.sh
    owner=root
    group=root
    mode=0555

- name: Install support packages (Debian/Ubuntu)
  package:
    pkg={{item}}
    state=latest
  with_items:
    - dmtcp
    - libopenmpi-dev
    - openmpi-bin
  when: '{{is_debian_or_ubuntu}}'


- name: Install SLURM packages (RHEL-compatible)
  package:
    name={{item}}
    state=present
  with_items:
    - openmpi-devel
  when: 'is_rhel_compatible'


- name: Enable SELinux (RHEL-family)
  selinux:
    policy=targeted
    state=enforcing
  when: 'is_rhel_compatible'

- name: Restore SELinux labels on `/` (RHEL-family)
  command: |
    restorecon -r /
  when: 'is_rhel_compatible'

