---

- name: Provide workaround for YAML syntax error in lines containing colon+space
  set_fact:
    __colon__: ':'
  tags:
    - cloud-init

- name: Allow package updates
  set_fact:
    pkg_install_state: 'latest'
  when: 'upgrade_packages|default(True)|bool'

- name: Disallow package updates
  set_fact:
    pkg_install_state: 'present'
  when: 'not upgrade_packages|default(True)|bool'

- include: 'init-{{ansible_os_family}}.yml'
- include: hosts.yml hosts={{groups.all}}
- include: hostname.yml
- include: netgroup.yml
- include: 'software-{{ansible_os_family}}.yml'
- include: ssh_auth.yml
