---

#
# Install Lua plus all needed packages for running Lmod
#

- name: Install Lua from the OS repository (Debian-compatible)
  apt:
    name: '{{ item }}'
    state: '{{ pkg_install_state }}'
    allow_unauthenticated: '{{ not insecure_https_downloads|default("no")|bool }}'
  with_items:
    # Luarocks requires Lua 5.1, at least on Ubuntu 16.04
    - lua5.1
    - liblua5.1-dev
    - luarocks
  when: '{{ is_debian_compatible }}'

- name: Install Lua from the OS repository (RHEL-compatible)
  yum:
    name: '{{ item }}'
    state: '{{ pkg_install_state }}'
  with_items:
    - lua
    - lua-devel
    - luarocks
  when: '{{ is_rhel_compatible }}'


- name: Find out actual installed Lua version
  command: |
    lua -e 'print(string.sub(_VERSION, 5))'
  register: _lua_version


- name: Make installed Lua version available to playbooks
  set_fact:
    lua_version: '{{ _lua_version.stdout }}'


- name: Load Lua-related settings at login time
  template:
    dest: /etc/profile.d/lua.sh
    src: etc/profile.d/lua.sh.j2
    mode: 0444


- name: Install additional packages needed by Lmod
  command: |
    luarocks install {{item}}
  args:
    creates: '/usr/local/lib/luarocks/rocks/{{item}}'
  with_items:
    - bit32
    - lua-term
    - luafilesystem
    - luaposix
