---
- name: patch munge on Ubuntu 14.04
  lineinfile: dest=/etc/default/munge line='OPTIONS="--force"' regexp='^OPTIONS=' state=present
  when: is_ubuntu_trusty
  tags:
    - munge

- name: configure munge
  action: copy src=slurm/files/etc/munge/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=0400
  notify: restart munge
  tags: 
    - munge

- name: munge service
  action: service name=munge state=started
  tags: 
    - munge
