---

- name: Load GlusterFS service names for RHEL-compatible
  set_fact:
    glusterfs_server_services:
      - glusterd
      - glusterfsd
      - glusterfssharedstorage

# Service names are different across GlusterFS versions;
# provide exceptions for older releases (last updated 2018-11-06)
- name: Load GlusterFS service names for RHEL-compatible (older GlusterFS releases)
  set_fact:
    glusterfs_server_services:
        - glusterd
        - glusterfsd
  when: glusterfs_version in ['3.8', '3.10', '3.11']


- name: Make GlusterFS release repo available to YUM
  yum:
    name: "centos-release-gluster{{ glusterfs_version | replace('.', '') }}"
  tags:
    - gluster
    - glusterfs-server
