---
- include: init-{{ ansible_os_family }}.yml

# for once, package names are the same on Debian/Ubuntu and RHEL/CentOS
- name: Install GlusterFS server packages
  package:
    name: '{{item}}'
    state: '{{ pkg_install_state }}'
  with_items:
    - glusterfs-server
    - glusterfs-client
  tags:
    - gluster
    - glusterfs-server


- name: Ensure the GlusterFS service is running
  service:
    name: '{{ item }}'
    state: 'started'
  # Service names are different across GlusterFS versions.
  #
  # This is implemented as a two-level hash table: the `init-XXX.yml`
  # files define `glusterfs_server_services` as a mapping from
  # `glusterfs_version` (string) to list of service names.
  #
  with_items: '{{ glusterfs_server_services[glusterfs_version] }}'
  tags:
    - gluster
    - glusterfs-server


- name: Configure peers (only on the first host)
  shell: |
    gluster peer probe '{{item}}'
  with_items: '{{groups.glusterfs_server}}'
  when: is_glusterfs_main_server_node
  tags:
    - gluster
    - glusterfs-server


# build and export volumes
- include: export.yml
  with_items: '{{GLUSTERFS_VOLUMES}}'
  tags:
    - gluster
    - glusterfs-server
