---

- name: Load configuration and service names (RHEL-compatible)
  set_fact:
    # map config file names across distributions
    configfile:
      'etc/iptables/rules.v4': '/etc/sysconfig/iptables'
      'etc/iptables/rules.v6': '/etc/sysconfig/ip6tables'
    # same for init service names
    service:
      'iptables':  'iptables'
      'ip6tables': 'ip6tables'
    reload: 'reload iptables'
  when: '{{is_rhel_compatible}}'

    
- name: Load configuration and service names (RHEL6-compatible)
  set_fact:
    packages:
      - iptables
      - iptables-ipv6
  when: '{{is_rhel6_compatible}}'


- name: Load configuration and service names (RHEL7-compatible)
  set_fact:
    packages:
      - iptables
      - iptables-services
  when: '{{is_rhel7_compatible}}'
