---

- name: Load configuration and service names (Debian/Ubuntu)
  set_fact:
    # map config file names across distributions
    configfile:
      'etc/iptables/rules.v4': '/etc/iptables/rules.v4'
      'etc/iptables/rules.v6': '/etc/iptables/rules.v6'
    # same for init service names
    service:
      'iptables':  'netfilter-persistent'
      'ip6tables': 'netfilter-persistent'
    # on Debian 8, issuing `systemctl reload netfilter-persistent`
    # fails with error "Failed to reload netfilter-persistent.service:
    # Job type reload is not applicable for unit
    # netfilter-persistent.service."  However, using `restart` instead
    # of `reload` could break existing connections (not good when
    # resizing), so do nothing and hope for the best...
    reload: 'no-op'
  when: ({{ is_ubuntu_15_10_or_later }} or {{ is_debian_8_or_later }}) 


- name: Load configuration and service names (older Debian/Ubuntu)
  set_fact:
    # map config file names across distributions
    configfile:
      'etc/iptables/rules.v4': '/etc/iptables/rules.v4'
      'etc/iptables/rules.v6': '/etc/iptables/rules.v6'
    # same for init service names
    service:
      'iptables':  'iptables-persistent'
      'ip6tables': 'iptables-persistent'
    reload: 'reload iptables'
  when: not ({{ is_ubuntu_15_10_or_later }} or {{ is_debian_8_or_later }})


- name: Load package names (Debian/Ubuntu)
  set_fact:
    packages:
      - iptables
      - iptables-persistent
  when: is_debian_compatible
